### ISSUE TITLE
PDF Expert

### ISSUE THREAD

**Issue by bytxk** [Cyberenchanter/scripts#1]
大佬有空能不能更新一下PDF expert解锁vip的脚本，新的版本失效了
https://raw.githubusercontent.com/langkhach270389/Scripting/master/Pdfexpert.vip.js

**Comment by cpphut** [comment]
PDF expert 7已经更换了授权方式，现采用直接与App Store对接的方式查询授权而不再通过自己的网站查询。由于iOS的安全限制，目前无法对苹果的地址进行mitm攻击因此这类软件目前无解

**Comment by bytxk** [comment]
那看来只有抓包旧版app，解锁之后再升级了。谢谢大佬！发自我的iPhone------------------ Original ------------------From: cpphut  <notifications@github.com>Date: Sat,Mar 6,2021 6:46 PMTo: cpphut/surge_module <surge_module@noreply.github.com>Cc: bytxk <xk954738429@gmail.com>, Author <author@noreply.github.com>Subject: Re: [cpphut/surge_module] PDF Expert (#1)
PDF expert 7已经更换了授权方式，现采用直接与App Store对接的方式查询授权而不再通过自己的网站查询。由于iOS的安全限制，目前无法对苹果的地址进行mitm攻击因此这类软件目前无解

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cpphut/surge_module/issues/1#issuecomment-791910694",
"url": "https://github.com/cpphut/surge_module/issues/1#issuecomment-791910694",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
